const select=(name,title,options)=>`<label class="job-field"><span>${title}</span><select name="${name}" id="filter-${name}"><option value="">${({role:'All roles',country:'All countries',company:'All companies',mode:'Any workplace',stage:'All career stages',type:'All job types',seniority:'All levels',skill:'All skills',period:'Any pay period',time:'Any posting date'})[name]}</option>${options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label>`;
const roles=[['software-engineering','SDE / Software'],['backend','Backend'],['frontend','Frontend'],['ai-ml','AI / ML'],['genai','GenAI'],['data','Data'],['devops-cloud','DevOps / Cloud'],['cybersecurity','Cybersecurity'],['ece-core','ECE'],['vlsi','VLSI'],['embedded','Embedded']];
export const jobsPage = `
<main id="main-content" class="jobs-shell">
 <section class="jobs-hero" aria-labelledby="jobs-title">
  <div class="jobs-hero-copy"><p class="eyebrow"><span class="status-dot"></span> WILSY JOBS / YOUR NEXT CHAPTER</p><h1 id="jobs-title">Find work<br><span>worth doing.</span></h1><p>Explore current roles, compare pay in rupees, and apply directly. Your next chapter starts with a clearer search.</p><a class="jobs-method" href="#how-jobs-work">Clear sources. Direct applications. <span></span></a></div>
  <aside class="jobs-insight" aria-label="Current job collection"><div class="insight-top"><span>THE OPPORTUNITY INDEX</span></div><div class="insight-total"><strong id="stat-total">—</strong><span>published opportunities</span></div><div class="insight-bottom"><div><strong id="stat-companies">—</strong><span>hiring companies</span></div><div><strong id="stat-remote">—</strong><span>remote roles</span></div></div><p><span>Explore the current collection.</span><span>Confirm availability with the employer.</span></p></aside>
 </section>
 <section class="jobs-workspace" aria-label="Search jobs">
  <form class="jobs-search" id="job-search-form" role="search"><div class="jobs-search-input"><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><label class="sr-only" for="job-search">Job title, company or keyword</label><input id="job-search" name="q" placeholder="Role, company or keyword" maxlength="200" autocomplete="off"><kbd aria-hidden="true">/</kbd></div><button class="jobs-search-submit" type="submit">Search jobs</button></form>
  <div class="jobs-quick" aria-label="Quick filters"><button type="button" data-quick="sort" data-value="posted">Latest posted</button><button type="button" data-quick="time" data-value="hour">Last hour</button><button type="button" data-quick="time" data-value="today">Today</button><span aria-hidden="true"></span><button type="button" data-quick="stage" data-value="internship">Internships</button><button type="button" data-quick="stage" data-value="fresher">Fresher</button><button type="button" data-quick="stage" data-value="new-grad">New grad</button><button type="button" data-quick="mode" data-value="remote">Remote</button><button type="button" id="saved-toggle" aria-pressed="false">Saved <span id="saved-count">0</span></button></div>
  <div class="job-workbench" aria-label="Your search tools">
   <details class="saved-searches" id="saved-searches"><summary>Saved searches <span id="searches-count">0</span></summary><div class="saved-search-panel"><div class="saved-search-heading"><strong>Pick up where you left off.</strong><p>Saved on this browser. Reopen a search to see current results.</p></div><div id="saved-search-list"></div></div></details>
   <button type="button" id="save-search">Save this search</button><button type="button" id="share-search">Copy search link</button>
   <div class="job-density" role="group" aria-label="Results display"><button type="button" data-density="comfortable" aria-pressed="true">Comfortable</button><button type="button" data-density="compact" aria-pressed="false">Compact</button></div>
  </div><p class="workspace-status" id="workspace-status" role="status"></p>
  <div class="jobs-columns">
   <aside class="jobs-filters" id="jobs-filters" aria-label="Job filters"><div class="jobs-filter-heading"><h2>Refine your search</h2><button type="button" data-clear>Reset</button></div><form id="job-filter-form">
    ${select('role','Role',roles)}${select('country','Country',[])}${select('company','Company',[])}
    ${select('mode','Workplace',[['remote','Remote'],['hybrid','Hybrid'],['onsite','Onsite']])}
    ${select('stage','Career stage',[['internship','Internship'],['fresher','Fresher'],['new-grad','New grad'],['apprenticeship','Apprenticeship']])}
    ${select('type','Job type',[['full_time','Full time'],['part_time','Part time'],['contract','Contract'],['internship','Internship'],['temporary','Temporary'],['other','Other']])}
    <details class="extra-filters"><summary>Experience & skills <span>+</span></summary>${select('seniority','Seniority',[])}<label class="job-field"><span>Your experience (years)</span><input type="number" name="experience" id="filter-experience" min="0" max="60" step="0.5" placeholder="Any experience"></label>${select('skill','Skill',[])}<p class="filter-help">Experience matches structured ranges. Missing requirements are excluded when this filter is used.</p></details>
    <details class="extra-filters"><summary>Compensation <span>+</span></summary><label class="job-check"><input type="checkbox" name="salary" id="filter-salary" value="yes">Salary disclosed</label><p class="salary-display-label">₹ All amounts in Indian rupees</p>${select('period','Pay period',[['year','Per year'],['month','Per month'],['hour','Per hour'],['week','Per week'],['day','Per day']])}<label class="job-field"><span>Minimum pay (INR)</span><input type="number" name="minimum" id="filter-minimum" min="0" max="1000000000" step="100" placeholder="Select a pay period" disabled></label><p class="filter-help">Includes ranges reaching your amount. Converted pay is an INR estimate; select a period to compare like for like.</p></details>
    <details class="extra-filters"><summary>More preferences <span>+</span></summary><label class="job-check"><input type="checkbox" name="visa" id="filter-visa" value="yes">Visa sponsorship stated</label><label class="job-check"><input type="checkbox" name="relocation" id="filter-relocation" value="yes">Relocation stated</label>${select('time','Posting date',[['hour','Last hour'],['today','Today (UTC)'],['week','Last 7 days']])}<p class="filter-help">Posting filters use employer dates. Last hour requires an exact timestamp; unknown dates are excluded.</p></details>
   <button type="button" class="filter-apply" id="job-filter-apply">Show matching jobs</button></form><a class="jobs-directory-card" href="/companies#companies"><span>LOOK BEYOND THE LISTING</span><strong>Meet your next company.</strong><span>Explore 1,000 profiles</span></a></aside>
   <div class="jobs-results-area"><div class="jobs-toolbar"><div><p class="eyebrow">YOUR NEXT OPPORTUNITY</p><h2 id="job-results-heading" tabindex="-1"><span id="job-count">Finding opportunities…</span></h2></div><div class="jobs-toolbar-actions"><button type="button" id="job-filter-toggle" aria-expanded="false" aria-controls="jobs-filters">Filter jobs</button><label class="sr-only" for="job-sort">Sort jobs</label><select id="job-sort"><option value="found">Recently found</option><option value="posted">Employer posting date</option></select><button type="button" id="job-refresh" aria-label="Refresh job results">Refresh</button></div></div><div id="job-active-filters" class="job-active-filters"></div><p id="job-connection" class="jobs-connection" role="status">Connecting to the current job collection…</p><div id="job-feedback" role="status" class="jobs-feedback"></div><div id="job-results" class="job-results" aria-busy="true"><div class="job-skeleton"></div><div class="job-skeleton"></div><div class="job-skeleton"></div></div><nav id="job-pagination" class="job-pagination" aria-label="Job result pages"></nav><p class="jobs-date-note">“Found” is when WILSY discovered a role. “Posted” is supplied by the employer or recruiting platform. Unknown details stay unspecified.</p></div>
  </div>
 </section>
 <section class="jobs-explainer" id="how-jobs-work"><div><p class="eyebrow">A MORE INFORMED NEXT MOVE</p><h2>Opportunity, with context.</h2><p>WILSY helps you discover jobs. Applications happen directly on the linked recruiting site.</p></div><article><span>01 / SOURCES</span><h3>Know where it comes from.</h3><p>Every listing links to its source. Employer verification and the latest recorded check are shown when available.</p></article><article><span>02 / DETAILS</span><h3>Clarity before you click.</h3><p>Compare location, experience and pay. Remote eligibility, visa support and salaries are only shown as stated.</p></article><article><span>03 / YOUR MOVE</span><h3>Make a thoughtful shortlist.</h3><p>Save roles on this device, explore company profiles, then confirm requirements and apply with the employer.</p></article></section>
</main>
<dialog class="job-detail-dialog" id="job-detail" aria-labelledby="job-detail-title"><button class="job-dialog-close" id="job-detail-close" type="button" aria-label="Close job details">Close</button><div id="job-detail-body"></div></dialog>
<section class="compare-tray" id="compare-tray" aria-label="Selected jobs for comparison" hidden><div class="compare-tray-copy"><strong id="compare-count">0 roles selected</strong><span>Compare the details that matter.</span></div><div class="compare-tray-items" id="compare-tray-items"></div><div class="compare-tray-actions"><button type="button" id="compare-clear">Clear</button><button type="button" id="compare-open" disabled>Compare roles</button></div><span class="sr-only" id="compare-status" role="status"></span></section>
<dialog class="compare-dialog" id="compare-dialog" aria-labelledby="compare-title"><div class="compare-dialog-heading"><div><p class="eyebrow">YOUR NEXT MOVE / SIDE BY SIDE</p><h2 id="compare-title">Find your better fit.</h2><p>A snapshot of the roles you selected. Confirm current details with each employer.</p></div><button type="button" id="compare-close" aria-label="Close job comparison">Close</button></div><p class="compare-scroll-hint">Scroll sideways to see every role.</p><div class="compare-table-scroll" tabindex="0" role="region" aria-label="Job comparison table; scroll horizontally for more roles"><table class="compare-table" id="compare-table"></table></div><p class="compare-footnote">Unknown details stay unspecified. Pay periods and locations may differ; INR conversions are estimates.</p></dialog>
<noscript><div class="noscript">Live job search needs JavaScript. You can still browse the <a href="/companies">company directory and career links</a>.</div></noscript>
<script type="module" src="/js/jobs.js"></script>`;
