const select=(key,title,options=[])=>`<label class="hack-field"><span>${title}</span><select id="hack-${key}" name="${key}"><option value="">All ${title.toLowerCase()}</option>${options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label>`;
export const hackathonsPage=`<main id="main-content" class="hack-shell">
 <section class="hack-hero"><div><p class="eyebrow"><span></span> WILSY HACKATHONS</p><h1>Build something<br><span>worth showing.</span></h1><p>Find your next challenge. Explore verified hackathons, understand the prizes, and go straight to the official registration.</p><div class="hack-hero-links"><a href="#hackathon-search">Explore challenges <span>↓</span></a><a href="/jobs">Looking for a role?</a></div></div><aside class="hack-index" aria-label="Current hackathon collection"><div class="hack-index-top"><span>THE CHALLENGE INDEX</span></div><strong id="hack-stat-total">—</strong><p>verified hackathons</p><div class="hack-index-bottom"><div><strong id="hack-stat-online">—</strong><span>online events</span></div><div><strong id="hack-stat-prizes">—</strong><span>cash prizes stated</span></div></div></aside></section>
 <section id="hackathon-search" class="hack-workspace" aria-label="Find hackathons">
  <form id="hack-search-form" class="hack-search" role="search"><label for="hack-search" class="sr-only">Search hackathons, organizers or skills</label><input id="hack-search" type="search" maxlength="200" placeholder="Search hackathons, organizers or skills" autocomplete="off"><button type="submit">Find a challenge <span></span></button></form>
  <div class="hack-quick" aria-label="Quick filters"><button type="button" data-hack-quick="mode" data-value="online">Online</button><button type="button" data-hack-quick="when" data-value="upcoming">Upcoming</button><button type="button" data-hack-quick="when" data-value="ongoing">In progress</button><button type="button" data-hack-quick="when" data-value="deadline">Deadlines · next 30 days</button><button type="button" data-hack-quick="cash" data-value="yes">Cash prizes</button><button type="button" id="hack-saved" aria-pressed="false">Saved <span id="hack-saved-count">0</span></button></div>
  <form id="hack-filter-form" class="hack-filters">${select('mode','Format',[['online','Online'],['offline','Offline'],['hybrid','Hybrid']])}${select('country','Country')}${select('theme','Theme')}${select('team','Team size',[['solo','Solo entries allowed'],['team','Team entries allowed']])}<button type="button" data-hack-reset>Reset filters</button></form>
  <div class="hack-toolbar"><div><p class="eyebrow">IDEAS START HERE</p><h2 id="hack-results-heading" tabindex="-1"><span id="hack-count">Finding challenges…</span></h2></div><div><label class="sr-only" for="hack-sort">Sort hackathons</label><select id="hack-sort"><option value="start">Start date</option><option value="deadline">Registration deadline</option><option value="found">Recently found</option></select><button type="button" id="hack-refresh" aria-label="Refresh hackathons">Refresh</button></div></div>
  <div id="hack-chips" class="hack-chips"></div><p id="hack-connection" class="hack-connection" role="status">Connecting to the current collection…</p><p id="hack-feedback" class="hack-feedback" role="status"></p>
  <div id="hack-results" class="hack-results" aria-busy="true"><div class="hack-skeleton"></div><div class="hack-skeleton"></div><div class="hack-skeleton"></div></div><nav id="hack-pagination" class="hack-pagination" aria-label="Hackathon result pages"></nav>
 </section>
 <section class="hack-principles"><div><p class="eyebrow">MORE CONTEXT. BETTER DECISIONS.</p><h2>Know the challenge<br>before you join.</h2></div><article><span>01</span><h3>Verified sources</h3><p>Organizer pages and established platforms, with official registration links and the latest recorded source check.</p></article><article><span>02</span><h3>Prizes, clearly explained</h3><p>Published prize pools and individual awards stay separate. Undisclosed amounts are never filled in.</p></article><article><span>03</span><h3>Eligibility comes first</h3><p>Check team limits, participation rules, dates and venue details before registering with the organizer.</p></article></section>
 </main><dialog id="hack-detail" class="hack-detail" aria-labelledby="hack-detail-title"><button id="hack-close" class="hack-close" type="button" aria-label="Close hackathon details">Close</button><div id="hack-detail-body"></div></dialog><noscript><div class="noscript">Live hackathon search needs JavaScript. You can browse our <a href="/guides">career guides</a> and <a href="/companies">company directory</a> without it.</div></noscript><script type="module" src="/hackathons.js"></script>`;
